# Generated by Django 5.0.4 on 2024-05-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=30)),
                ('corp_num', models.CharField(max_length=30)),
                ('corp_jamo', models.CharField(max_length=30)),
            ],
        ),
    ]
