# Generated by Django 5.0.4 on 2024-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_dart',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
